<?php

define('ASSOCIATION_ID', '3617083');

/**
 * Implements hook_form_alter()
 **/
function members360_auth_form_alter(&$form, &$form_state, $form_id)
{
	switch($form_id)
	{
		case 'user_login_block':
		case 'user_login':	
			foreach($form['#validate'] as $key => $value)
			{
				if($value == 'user_login_authenticate_validate')
					$form['#validate'][$key] = 'members360_auth_validate';
			}							
			break;					
	}
}

/**
 * Replaces user login submit with authentication against Members360 SOAP login
 **/
function members360_auth_validate($form, &$form_state)
{
	$user = $form_state['values']['name'];
	$pass = $form_state['values']['pass'];
	$status = members360_auth_authenticate($user, $pass);	
	switch($status)	
	{
		case 'UserLocked':
			form_set_error('name', t('Your membership has expired. Please contact the CAJPA office.'));
			break;
			
		case 'SessionOk':
			$account = user_load_by_name($user);
			$form_state['uid'] = $account->uid;
			break;
			
		default:
			form_set_error('name', t('Invalid Login.'));
	}
}

/**
 * Send authentication information to Members360
 **/
function members360_auth_authenticate($user, $pass)
{	
	$fields = array(
		'pAssociationId' => ASSOCIATION_ID,
		'pUserName' => $user,
		'pPassword' => $pass,
		'pApplicationType' => 'Members360',
	);
	
	$output = array();
	foreach($fields as $key => $value)
	{
		$output[] = $key.'='.$value;
	}
	$fields = implode('&', $output);
	
	$ch = curl_init();
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($ch, CURLOPT_URL, 'https://sso.affiniscape.com/LoginService.asmx/AuthenticateUser');
	curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, FALSE); 
    curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, FALSE); 
	curl_setopt($ch, CURLOPT_POST, true);
	curl_setopt($ch, CURLOPT_POSTFIELDS, $fields);	
	$output = curl_exec($ch);
	curl_close($ch);	
	if(preg_match('/SessionStatus>(.*)<\/SessionStatus/', $output, $matches))
	{	
		$status = $matches[1];		
		return $status;		
	}
	return false;
}